import os
from dotenv import load_dotenv
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options  
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By
from selenium import webdriver
import time 
import random
from datetime import datetime
from Email import send_alert
from LogIn import ucla_login


load_dotenv()


driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
wait = WebDriverWait(driver, 300, poll_frequency=0.1)
class_URL = "https://sa.ucla.edu/ro/ClassSearch/Results?SubjectAreaName=Computer+Science+(COM+SCI)&CrsCatlgName=118+-+Computer+Network+Fundamentals&t=26S&sBy=subject&subj=COM+SCI&catlg=0118&cls_no=%25&undefined=Go&btnIsInIndex=btn_inIndex"


def first_pass():
    driver.get(class_URL)

    #lec checkbox
    lec_id = "187350200_COMSCI0118-checkbox"
    wait.until(EC.presence_of_element_located((By.ID, lec_id)))
    driver.execute_script("document.getElementById(arguments[0]).click();", lec_id)

            
    #disc checkbox
    disc_id = "187350201_187350200_COMSCI0118-checkbox"
    wait.until(EC.presence_of_element_located((By.ID, disc_id)))
    driver.execute_script("document.getElementById(arguments[0]).click();", disc_id)

    #pte button
    pte_button = wait.until(EC.presence_of_element_located((By.ID, "btn_Pte")))
    driver.execute_script("arguments[0].click();", pte_button)
def enroll_button(pte_guess_int):
    pte_input = wait.until(EC.element_to_be_clickable((By.ID, "txtbox_enroll_warning_pte_flyout_pte")))
    pte_input.clear()

    pte_guess_str = f"{pte_guess_int:05}"
    pte_input.send_keys(pte_guess_str)
    driver.execute_script("arguments[0].blur();", pte_input)

        
    #warning buttons
    warning_ids = [
        "enroll_warning_flyout_warning_checkbox1",
        "enroll_warning_flyout_warning_checkbox3",
        "enroll_warning_flyout_warning_checkbox5"
    ]
    for cb_id in warning_ids:
        element = wait.until(EC.presence_of_element_located((By.ID, cb_id)))

        # this block was generated by gemini, since idk wtf to do
        driver.execute_script("""
            var el = document.getElementById(arguments[0]);
            if (el) {
                el.click();
                // Force the 'checked' property just in case the UI is laggy
                if (!el.checked) {
                    el.checked = true;
                }
                // Trigger events so the website's backend logic knows we clicked
                el.dispatchEvent(new Event('change', { bubbles: true }));
                el.dispatchEvent(new Event('input', { bubbles: true }));
            }
        """, cb_id)
    
    
    wait.until(EC.element_to_be_clickable((By.ID, "btn_Enroll")))
    driver.execute_script("document.getElementById('btn_Enroll').click();")   
def new_pte_button(pte_guess_int_1):
    combined_xpath = "//*[contains(text(), 'PTE is invalid') or contains(text(), 'An error occurred')]"

    error_element = wait.until(
        EC.presence_of_element_located((By.XPATH, combined_xpath))
    )
    error_text = error_element.text 

    if "PTE is invalid" not in error_text:
        print("REDOOOINGGG")
        first_pass()
        
    pte_guess_str = f"{pte_guess_int_1:05}"
    print(f"{datetime.now()}: Tried PTE {pte_guess_str} - Invalid")

    #pte button
    pte_button = wait.until(EC.presence_of_element_located((By.ID, "btn_Pte")))
    driver.execute_script("arguments[0].click();", pte_button)
def create_tabs_first_pass():
    for tab in tabs:
        driver.switch_to.window(tab)
        first_pass()
        

def enroll_button_check():
    try:
        pte_input = driver.find_element(By.ID, "txtbox_enroll_warning_pte_flyout_pte")
        return pte_input.is_displayed() and pte_input.is_enabled()
    except NoSuchElementException:
        return False

def new_pte_button_check():
    combined_xpath = "//*[contains(text(), 'PTE is invalid') or contains(text(), 'An error occurred')]"
    try:
        error_element = driver.find_element(By.XPATH, combined_xpath)
        return error_element.is_displayed()
    except NoSuchElementException:
        return False



#initialize and first pass all tabs
ucla_login(driver)
tab1 = driver.current_window_handle
driver.execute_script("window.open('');")
tab2 = driver.window_handles[1]
driver.execute_script("window.open('');")
tab3 = driver.window_handles[2]
driver.execute_script("window.open('');")
tab4 = driver.window_handles[3]
driver.execute_script("window.open('');")
tab5 = driver.window_handles[4]
driver.execute_script("window.open('');")
tab6 = driver.window_handles[5]
driver.execute_script("window.open('');")
tab7 = driver.window_handles[6]
driver.execute_script("window.open('');")
tab8 = driver.window_handles[7]
driver.execute_script("window.open('');")
tab9 = driver.window_handles[8]
driver.execute_script("window.open('');")
tab10 = driver.window_handles[9]
driver.execute_script("window.open('');")
tab11 = driver.window_handles[10]
driver.execute_script("window.open('');")
tab12 = driver.window_handles[11]
driver.execute_script("window.open('');")
tab13 = driver.window_handles[12]
driver.execute_script("window.open('');")
tab14 = driver.window_handles[13]
driver.execute_script("window.open('');")
tab15 = driver.window_handles[14]
driver.execute_script("window.open('');")
tab16 = driver.window_handles[15]
driver.execute_script("window.open('');")
tab17 = driver.window_handles[16]
driver.execute_script("window.open('');")
tab18 = driver.window_handles[17]
driver.execute_script("window.open('');")
tab19 = driver.window_handles[18]
driver.execute_script("window.open('');")
tab20 = driver.window_handles[19]

tabs = [tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8, tab9, tab10, tab11, tab12, tab13, tab14, tab15, tab16, tab17, tab18, tab19, tab20]
tabs_guess = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
create_tabs_first_pass()



tabs_state = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
tabs_xpath_reload = [0] * 20
pte_guess = 21006
while True:
    for i, tab in enumerate(tabs):
        driver.switch_to.window(tab)
        if tabs_state[i] == 0:
            # if this is not true clickable then skip this tab, DO NOT UPDATE STATE 
            if enroll_button_check(): 
                pte_guess = pte_guess + 1
                tabs_guess[i] = pte_guess
                tabs_state[i] = 1 #update state to 1
                enroll_button(tabs_guess[i]) 

        elif tabs_state[i] == 1:
            #check if pte button is clickable, if not then skip, DO NOT UPDATE STATE
            if new_pte_button_check():
                tabs_xpath_reload[i] = 0
                new_pte_button(tabs_guess[i])
                tabs_state[i] = 0
                print(f"tab {i} guessed {tabs_guess[i]}")
            else:
                tabs_xpath_reload[i] = tabs_xpath_reload[i] + 1
                if (tabs_xpath_reload[i] > 50): 
                    time.sleep(60*60*2)
                    print(f"tab {i} is reloading due to xpath failure for pte {tabs_guess[i]}")

    
       
        


    
    
    
























    
